# 파이썬 4월 6일 강의 복습
> "7월 1일"

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최석진
- categories: [Python]

## numpy (선언, 브로드캐스팅, 수학연산, 인덱싱, reshape, 랜덤으로 생성, 행렬관련기능)
> July 1, 2022

### import

In [1]:
import numpy as np

### 넘파이 공부 1단계

#### 선언

In [2]:
a=np.array([1,2,3]) #list로 만들고 ndarray화 시킴
l=[1,2,3]

#### 기본연산 브로드캐스팅

In [3]:
a+1 ## [1,2,3]+1=[2,3,4]

array([2, 3, 4])

In [4]:
l+1 #list는 브로드캐스팅 불가

TypeError: can only concatenate list (not "int") to list

In [5]:
a*2

array([2, 4, 6])

In [6]:
l*2

[1, 2, 3, 1, 2, 3]

In [7]:
a/2

array([0.5, 1. , 1.5])

In [8]:
l/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [9]:
a**2

array([1, 4, 9])

In [10]:
l**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [11]:
a%2

array([1, 0, 1])

In [12]:
l%2

TypeError: unsupported operand type(s) for %: 'list' and 'int'

기타 수학연산 지원 (루트,로그,sin,cos)

In [15]:
np.sqrt(a), np.sqrt(l)

(array([1.        , 1.41421356, 1.73205081]),
 array([1.        , 1.41421356, 1.73205081]))

In [16]:
np.log(a),np.log(l)

(array([0.        , 0.69314718, 1.09861229]),
 array([0.        , 0.69314718, 1.09861229]))

In [17]:
np.exp(a),np.log(l)

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([0.        , 0.69314718, 1.09861229]))

In [19]:
np.sin(a),np.sin(l)

(array([0.84147098, 0.90929743, 0.14112001]),
 array([0.84147098, 0.90929743, 0.14112001]))

### 넘파이 공부 2단계

#### 인덱싱 1차원

`-` 선언

In [21]:
l=[11,22,33,44,55,66]
a=np.array(l)

`-` 인덱스로 접근

In [23]:
l[0],l[1],l[2],l[3],l[-2],l[-1]

(11, 22, 33, 44, 55, 66)

In [24]:
a[0],a[1],a[2],a[3],a[-2],a[-1]

(11, 22, 33, 44, 55, 66)

`-` `:` 이용 (슬라이싱)

In [25]:
l[2:4]

[33, 44]

In [26]:
a[2:4]

array([33, 44])

`-` 정수배열에 의한 인덱싱

In [27]:
a[[0,2,4]] #index=0,index=2,index=4에 해당하는 원소를 뽑고 싶음

array([11, 33, 55])

In [29]:
l[[0,2,4]] #리스트는 불가능

TypeError: list indices must be integers or slices, not list

`-` bool값에 의한 인덱싱

In [30]:
a[[True,False,True,False,True,False]]

array([11, 33, 55])

In [31]:
a<33

array([ True,  True, False, False, False, False])

In [32]:
a[a<33]

array([11, 22])

In [33]:
l<33 #리스트는 불가능

TypeError: '<' not supported between instances of 'list' and 'int'

#### 인덱싱 2차원

`-` 중첩리스트와 2차원 np.array 선언

In [34]:
A=[[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]]
A2=np.array(A)

In [35]:
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [36]:
A

[[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8], [-5, -6, -7, -8]]

`-` A의 원소 인덱싱

In [37]:
A[0][0] #(1,1)

1

In [38]:
A[1][2] #(2,3)

-3

In [40]:
A[-1][0] #(4,1)

-5

`-` A2의 원소 인덱싱

In [41]:
A2[0][0]

1

In [42]:
A2[1][2]

-3

In [43]:
A2[-1][0]

-5

`-` A2 즉, numpy에서만 되는 기술 

In [45]:
A2[0,0]

1

In [46]:
A2[1,2]

-3

In [47]:
A2[-1,0]

-5

`-` 정수배열에 의한 인덱싱 & 슬라이싱!

In [48]:
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [49]:
A2[0,0:2] #1행1열, 1행2열

array([1, 2])

In [50]:
A2[0,:] #1행

array([1, 2, 3, 4])

In [51]:
A2[0] #1행

array([1, 2, 3, 4])

In [53]:
A2[[0,2],:] #1행, 3행

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
A2[:,0] #1열

array([ 1, -1,  5, -5])

In [55]:
A2[:,[0]] #1열

array([[ 1],
       [-1],
       [ 5],
       [-5]])

In [56]:
A2[:,[0,2]] # 1열, 3열

array([[ 1,  3],
       [-1, -3],
       [ 5,  7],
       [-5, -7]])

In [57]:
A2[0:2,[0,2]] #1행~2행 // 1열, 3열

array([[ 1,  3],
       [-1, -3]])

#### 1차원 배열의 선언

`-` 리스트나 튜플을 선언하고 형변환

In [59]:
np.array((1,2,3)) #tuple->numpy array

array([1, 2, 3])

In [61]:
np.array([1,2,3]) #list->numpy array

array([1, 2, 3])

`-` range()를 이용해서 선언하고 형변환

In [62]:
np.array(range(10)) #range(10) -> numpy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`-` np.zeros, np.ones

In [63]:
np.zeros(3)

array([0., 0., 0.])

In [64]:
np.ones(4)

array([1., 1., 1., 1.])

`-` np.linspace

In [65]:
np.linspace(0,1,12) #0에서 시작하고 1에서 끝남 (양끝넘 모두 포함)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [66]:
len(np.linspace(0,1,12)) 

12

`-` np.arrange

In [68]:
np.arange(5) #np.array(range(5))

array([0, 1, 2, 3, 4])

In [69]:
np.arange(1,6) #np.array(range(1,6))

array([1, 2, 3, 4, 5])

#### reshape

In [70]:
a=np.array([11,22,33,44,55,66])
a ##길이 6인 벡터

array([11, 22, 33, 44, 55, 66])

In [71]:
a.reshape(2,3) #(2,3)인 matrix라 생각해도 무방

array([[11, 22, 33],
       [44, 55, 66]])

> reshape은 a자체를 변화시키는 것은 아님

In [72]:
a #a는 그대로임

array([11, 22, 33, 44, 55, 66])

In [73]:
b=a.reshape(2,3)
b

array([[11, 22, 33],
       [44, 55, 66]])

`-` 다시 b를 a처럼 바꾸고 싶다

In [74]:
b

array([[11, 22, 33],
       [44, 55, 66]])

In [75]:
b.reshape(6) #(2,3) matrix -> 길이 6인 벡터

array([11, 22, 33, 44, 55, 66])

`-` reshape with -1

In [76]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [77]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [78]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [79]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [80]:
a.reshape(5,-1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [81]:
a.reshape(12,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [82]:
b=a.reshape(12,-1)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [83]:
b.reshape(-1) #b를 다시 길이가 24인 벡터로!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### 2차원 배열의 선언

In [84]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
np.diag([1,2,3,-1])

array([[ 1,  0,  0,  0],
       [ 0,  2,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0,  0, -1]])

랜덤으로 배열 생성

In [88]:
np.random.randn(10) #표준정규분포에서 10개를 뽑음

array([ 0.64050501, -0.77307583,  0.09305379,  0.69274512,  1.99899153,
        0.3779905 ,  0.53780081,  0.09507327,  0.90555149,  1.18217057])

In [89]:
np.random.rand(10) #0~1사이에서 10개를 뽑음

array([0.61261792, 0.36564317, 0.88314963, 0.61544869, 0.61356166,
       0.04958533, 0.04479986, 0.39979467, 0.51598939, 0.18707705])

In [90]:
np.random.randn(4).reshape(2,2) #표준정규분포에서 4개를 뽑고 (2,2) ndarray로 형태변환

array([[-0.04726468, -1.54741047],
       [ 1.25439987, -1.62358495]])

In [91]:
np.random.rand(4).reshape(2,2) #0~1에서 4개를 뽑고 (2,2) ndarray로 형태변환

array([[0.33327773, 0.76453317],
       [0.50525275, 0.81001804]])

#### 행렬관련기능

In [94]:
A=np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [95]:
A.T #T는 전치행렬

array([[0, 2],
       [1, 3]])

In [96]:
np.linalg.inv(A) #np.linalg.inv는 역행렬을 구해주는 함수

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [97]:
A @ np.linalg.inv(A) #@는 행렬 곱을 수행

array([[1., 0.],
       [0., 1.]])