# 파이썬 4월 13일 강의 복습
> "7월 3일"

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최석진
- categories: [Python]

## numpy 
### (rand,randn,randint,choice,통계분포,np.where/np.argwhere,인덱싱고급,np.ix_)

In [1]:
import numpy as np

### 넘파이공부 5단계: 랜덤모듈

#### np.random.rand()

`-` 0~1 사이에서 10개의 난수 생성

In [2]:
np.random.rand(10)

array([0.40236218, 0.87443506, 0.45839405, 0.59640667, 0.75735355,
       0.40706425, 0.0733528 , 0.17604515, 0.86612186, 0.26403677])

`-`0~2사이에서 10개의 난수 생성

In [3]:
np.random.rand(10)*2

array([1.81799833, 0.41452248, 0.2863462 , 0.82510586, 0.47541581,
       1.39861094, 1.68476284, 1.27401562, 0.27471634, 1.19583407])

`-` 1~2사이에서 10개의 난수 생성

In [4]:
np.random.rand(10)+1

array([1.65355249, 1.54047511, 1.98523073, 1.85773949, 1.58000043,
       1.04275226, 1.09609135, 1.38568324, 1.09198105, 1.88517803])

`-` 1~3사이에서 10개의 난수 생성

In [6]:
np.random.rand(10)*2+1

array([2.11873837, 1.74166251, 2.09131209, 2.98637845, 2.09015142,
       2.69748809, 1.25176549, 2.09116953, 2.33496592, 1.65444888])

#### np.random.randn()

`-` N(0,1)에서 10개 추출

In [7]:
np.random.randn(10)

array([-0.20631419, -0.04131124,  0.72532655,  1.39103001, -0.64461439,
        0.56492181, -0.52680442, -0.35162868, -0.09135304,  0.40215028])

`-` N(1,1)에서 10개 추출

In [8]:
np.random.randn(10)+1

array([ 2.63425535, -0.17660609, -0.49076016,  0.62911989,  1.5310684 ,
        3.32368726,  1.99533253,  2.00592338, -0.14671444,  0.12775136])

`-` N(0,4)에서 10개 추출 (평균이 0이고 분산이 4인 분포)

In [9]:
np.random.randn(10)*2

array([ 0.12156013, -2.48216171,  1.86544445, -1.21163889, -2.38288207,
       -2.21207458,  1.0455293 , -0.40744864,  1.47241477, -0.98262694])

`-` N(3,4)에서 10개 추출

In [10]:
np.random.randn(10)*2+3

array([4.88302298, 2.40360439, 4.4385233 , 5.17978021, 3.64003266,
       2.55346388, 2.1418646 , 3.96931924, 6.06363415, 6.0878664 ])

#### np.random.randint()

`-`[0,7)의 범위에서 하나의 정수를 랜덤으로 생성

In [11]:
np.random.randint(7)

6

`-` [0,7)의 범위에서 20개의 정수를 랜덤으로 생성

In [12]:
np.random.randint(7,size=(20,))

array([5, 5, 5, 3, 4, 3, 4, 5, 3, 1, 1, 1, 2, 0, 0, 3, 6, 0, 1, 1])

`-`[0,7)의 범위에서 (2,2) shape으로 정수를 랜덤으로 생성

In [13]:
np.random.randint(7,size=(2,2))

array([[0, 0],
       [0, 1]])

`-` 위와 같은 코드를 아래와 같이 구현가능

In [14]:
np.random.randint(low=7,size=(5,5))

array([[4, 2, 1, 2, 3],
       [5, 4, 1, 6, 4],
       [4, 1, 1, 6, 4],
       [6, 5, 5, 5, 2],
       [4, 3, 4, 2, 3]])

`-`[10,20)의 범위에서 (5,5) shape 정수를 랜덤으로 생성

In [15]:
np.random.randint(low=10,high=20,size=(5,5))

array([[10, 11, 14, 13, 16],
       [10, 15, 18, 18, 18],
       [13, 19, 16, 12, 18],
       [10, 11, 14, 19, 14],
       [18, 13, 15, 14, 16]])

#### np.random.choice()

`-` [0,5) 에서 20개를 뽑음, 중복허용

In [17]:
np.random.choice(5,20)

array([2, 2, 2, 1, 0, 1, 1, 1, 3, 2, 2, 1, 3, 4, 1, 3, 3, 2, 1, 4])

- np.random.randint(5,size=(20,)) 와 같은 코드

`-` [0,1,2,3]에서 20개를 뽑음, 중복허용

In [18]:
np.random.choice([0,1,2,3],20)

array([0, 3, 0, 1, 0, 0, 1, 1, 0, 2, 0, 2, 1, 1, 3, 3, 3, 1, 2, 1])

`-`["apple","orange","banana"]에서 20개를 뽑음, 중복허용

In [19]:
np.random.choice(["apple","orange","banana"],20)

array(['orange', 'banana', 'banana', 'apple', 'orange', 'orange', 'apple',
       'banana', 'apple', 'orange', 'apple', 'orange', 'banana', 'banana',
       'orange', 'apple', 'apple', 'banana', 'apple', 'banana'],
      dtype='<U6')

`-`["apple","orange","banana"]에서 2개를 뽑음, 중복허용 X

In [21]:
np.random.choice(["apple","orange","banana"],2,replace=False)

array(['banana', 'orange'], dtype='<U6')

#### 통계분포

In [22]:
np.random.binomial(n=10,p=0.2,size=(5,)) #X1,....,X5 ~ B(10,0.2)

array([2, 1, 0, 1, 2])

In [23]:
np.random.normal(loc=10,scale=2,size=(5,)) #X1,...,X5 ~N(10,4)

array([ 8.13929528,  7.75328746, 11.09847732,  9.32163608, 11.38410008])

- np.random.randn(5)*2+10 와 같은코드

In [24]:
np.random.uniform(low=2,high=4,size=(5,)) #X1,...,X5 ~U(2,4)

array([3.69196416, 3.63529735, 3.58636484, 2.96146708, 2.66701839])

- np.random.rand(5)*2+2 와 같은코드

In [25]:
np.random.poisson(lam=5,size=(5,)) #X1,...,X5 ~Poi(5)

array([9, 4, 2, 7, 5])

### 넘파이공부 6단계: 기타 유용한 기본기능들

#### np.where,np.argwhere

`-` 1차원

In [26]:
a=np.array([0,0,0,1,0])
a

array([0, 0, 0, 1, 0])

In [27]:
np.where(a==1) #조건 a==1을 만족하는 인덱스를 출력하라

(array([3]),)

In [28]:
np.argwhere(a==1)

array([[3]])

`-` 2차원

In [29]:
np.random.seed(43052)
a=np.random.randn(12).reshape(3,4)
a

array([[ 0.38342049,  1.0841745 ,  1.14277825,  0.30789368],
       [ 0.23778744,  0.35595116, -1.66307542, -1.38277318],
       [-1.92684484, -1.4862163 ,  0.00692519, -0.03488725]])

In [30]:
np.where(a<0) # 조건을 만족하는 인덱스가 (1,2),(1,3),(2,0),(2,1),(2,3) 이라는 의미

(array([1, 1, 2, 2, 2]), array([2, 3, 0, 1, 3]))

In [31]:
np.argwhere(a<0) # 조건을 만족하는 인덱스가 (1,2),(1,3),(2,0),(2,1),(2,3) 이라는 의미

array([[1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3]])

In [32]:
a[np.where(a<0)] #조건을 만족하는 인덱스가 모두 출력 => 1차원 array로 출력

array([-1.66307542, -1.38277318, -1.92684484, -1.4862163 , -0.03488725])

In [33]:
a[np.argwhere(a<0)] #출력 불가능

IndexError: index 3 is out of bounds for axis 0 with size 3

`-` np.where의 특수기능

In [34]:
np.random.seed(43052)
a=np.random.randn(12).reshape(3,4)
a

array([[ 0.38342049,  1.0841745 ,  1.14277825,  0.30789368],
       [ 0.23778744,  0.35595116, -1.66307542, -1.38277318],
       [-1.92684484, -1.4862163 ,  0.00692519, -0.03488725]])

In [35]:
np.where(a<0,0,a) #ifelse같은 구문 // a<0을 체크 => 조건에 맞으면 0 => 조건에 안맞으면 a

array([[0.38342049, 1.0841745 , 1.14277825, 0.30789368],
       [0.23778744, 0.35595116, 0.        , 0.        ],
       [0.        , 0.        , 0.00692519, 0.        ]])

In [36]:
np.where(a<0,0,1) #a<0을 체크 => 조건에 맞으면 0 => 조건에 안맞으면 1

array([[1, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 0]])

`-` 요약

- np.where : 인덱스의 좌표를 읽는 가독성은 떨어짐, 그런데 조건에 맞는 원소를 출력하거나 처리하는 (특수기능) 목적으로는 좋은 함수

- np.argwhere : 인덱스의 좌표를 읽는 가독성은 좋음, 그런데 조건에 맞는 원소를 출력하거나 처리하는 기능은 떨어짐

#### 인덱싱고급

`-` 원래 a는 2d array

In [38]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

`-` 경우1 : 인덱싱 결과가 1d array로 나올 수 있음

In [40]:
a[0,:] # 인덱싱의 결과 축의 개수가 바뀜 / 2d array -> 1d array

array([0, 1, 2, 3])

`-` 경우2 : 인덱싱 결과가 2d array로 나오게 하기

In [41]:
a[[0,1],:] # 2d array -> 2d array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

`-` 경우1의 상황에서도 축의 개수를 유지하면서 인덱싱하려면?

In [42]:
a[[0],:]

array([[0, 1, 2, 3]])

In [43]:
a[:,[0]]

array([[0],
       [4],
       [8]])

`-` 차이를 이해

In [44]:
a[0,:],a[[0],:]

(array([0, 1, 2, 3]), array([[0, 1, 2, 3]]))

In [45]:
a[:,0],a[:,[0]]

(array([0, 4, 8]),
 array([[0],
        [4],
        [8]]))

#### np.ix_

`-` 인덱싱 비교

In [46]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
a[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [48]:
a[[0,1],0:2]

array([[0, 1],
       [4, 5]])

In [49]:
a[0:2,[0,1]]

array([[0, 1],
       [4, 5]])

그럼 a[[0,1],[0,1]] 결과 역시 동일 할 것임

In [50]:
a[[0,1],[0,1]]

array([0, 5])

- 실제로는 [a[0,0],a[1,1]]이 array로 나옴

`-` np.where에서 이미 관찰하였음

In [52]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
np.where(a%5==0)

(array([0, 1, 2]), array([0, 1, 2]))

In [54]:
a[np.where(a%5==0)]

array([ 0,  5, 10])

In [55]:
a[[0,1,2],[0,1,2]]

array([ 0,  5, 10])

`-` a[[0,1],[0,1]]이 a[0:2,0:2]를 의미하게 하려면 아래와 같이 작성

In [57]:
a[np.ix_([0,1],[0,1])]

array([[0, 1],
       [4, 5]])