# 파이썬 5월 6일 강의 복습
> "7월 6일"

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최석진
- categories: [Python]

## pandas 사용법

In [3]:
import numpy as np
import pandas as pd

### pandas 공부 1단계

데이터프레임 선언

`-` 방법1 : dictionary에서 만든다. 

In [4]:
pd.DataFrame({'att':[30,40,50],'mid':[50,60,70]})

att  mid
0   30   50
1   40   60
2   50   70

In [5]:
pd.DataFrame({'att':(30,40,50),'mid':(50,60,70)})

att  mid
0   30   50
1   40   60
2   50   70

In [6]:
pd.DataFrame({'att':np.array([30,40,50]),'mid':np.array([50,60,70])})

att  mid
0   30   50
1   40   60
2   50   70

`-` 방법2 : 2차원 ndarray에서 만든다.

In [7]:
np.arange(2*3).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
pd.DataFrame(np.arange(2*3).reshape(2,3))

0  1  2
0  0  1  2
1  3  4  5

열의 이름 부여

`-` 방법1 : 딕셔너리를 통해 만들면 딕셔너리의 key가 자동으로 열의 이름이 된다.

In [9]:
pd.DataFrame({'att':np.array([30,40,50]),'mid':np.array([50,60,70])})

att  mid
0   30   50
1   40   60
2   50   70

`-` 방법2 : pd.DataFrame()의 옵션에 columns를 이용

In [12]:
pd.DataFrame(np.arange(2*3).reshape(2,3),columns=['X1','X2','X3'])

X1  X2  X3
0   0   1   2
1   3   4   5

`-` 방법3 : df.columns에 원하는 열이름을 덮어씀 (1)

In [14]:
df=pd.DataFrame(np.arange(2*3).reshape(2,3))
df

0  1  2
0  0  1  2
1  3  4  5

In [15]:
df.columns=['X1','X2','X3']
df

X1  X2  X3
0   0   1   2
1   3   4   5

In [16]:
df.columns

Index(['X1', 'X2', 'X3'], dtype='object')

`-` 방법4 : df.columns에 원하는 열이름을 덮어씀 (2)

In [17]:
df=pd.DataFrame(np.arange(2*3).reshape(2,3))
df

0  1  2
0  0  1  2
1  3  4  5

In [18]:
df.columns=pd.Index(['X1','X2','X3'])
df

X1  X2  X3
0   0   1   2
1   3   4   5

방법4가 방법3의 방식보다 불필요한 에러를 방지할 수 있음.

In [19]:
df.columns, type(df.columns)

(Index(['X1', 'X2', 'X3'], dtype='object'), pandas.core.indexes.base.Index)

In [20]:
['X1','X2','X3'], type(['X1','X2','X3'])

(['X1', 'X2', 'X3'], list)

In [22]:
pd.Index(['X1','X2','X3']), type(pd.Index(['X1','X2','X3']))

(Index(['X1', 'X2', 'X3'], dtype='object'), pandas.core.indexes.base.Index)

행의 이름 부여

`-` 방법1 : 중첩 dict이면 nested dic의 key가 알아서 행의 이름으로 된다.

In [24]:
pd.DataFrame({'att':{'seokjin':30,'iu':40,'jk':50},'mid':{'seokjin':35,'iu':45,'jk':80}})

att  mid
seokjin   30   35
iu        40   45
jk        50   80

`-` 방법2 : pd.DataFrame()의 index 옵션 이용

In [25]:
pd.DataFrame({'att':[30,40,50],'mid':[35,45,80]},index=['seokjin','iu','jk'])

att  mid
seokjin   30   35
iu        40   45
jk        50   80

`-` 방법3 : df.index에 덮어씌움

In [28]:
df=pd.DataFrame({'att':[30,40,50],'mid':[35,45,80]})
df

att  mid
0   30   35
1   40   45
2   50   80

In [27]:
df.index=pd.Index(['seokjin','iu','jk'])
df

att  mid
seokjin   30   35
iu        40   45
jk        50   80

`-` 방법4 : df.set_index()를 이용하여 덮어씌운다.

In [29]:
df=pd.DataFrame({'att':[30,40,50],'mid':[35,45,80]})
df

att  mid
0   30   35
1   40   45
2   50   80

In [30]:
df.set_index(pd.Index(['seokjin','iu','jk']))

att  mid
seokjin   30   35
iu        40   45
jk        50   80

(주의) 아래는 에러가 난다.

In [31]:
df.set_index(['seokjin','iu','jk'])

KeyError: "None of ['seokjin', 'iu', 'jk'] are in the columns"

In [32]:
df.set_index([['seokjin','iu','jk']]) #꺽쇠를 한번 더 넣어주면 에러를 피할 수 있음.

att  mid
seokjin   30   35
iu        40   45
jk        50   80

#### 자료형,len,shape,for문의 반복변수

In [34]:
df=pd.DataFrame({'att':[30,40,50],'mid':[35,45,80]})
df

att  mid
0   30   35
1   40   45
2   50   80

`-` type

In [35]:
type(df)

pandas.core.frame.DataFrame

`-` len

In [36]:
len(df) #row

3

`-` shape

In [37]:
df.shape

(3, 2)

`-` for문의 반복변수

In [38]:
for k in df:
    print(k) #like dictionary

att
mid


In [39]:
for k in {'att':[30,40,50],'mid':[35,45,80]}:
    print(k)

att
mid


#### pd.Series

`-` 2차원 ndarray가 pd.DataFrame에 대응한다면 1차원 ndarray는 pd.Series에 대응

In [40]:
a=pd.Series(np.random.randn(10))
a

0   -0.412233
1   -2.301808
2   -0.567737
3    0.843052
4    0.037923
5   -0.889114
6   -0.513315
7   -1.045865
8    2.123853
9    1.017527
dtype: float64

In [41]:
type(a)

pandas.core.series.Series

In [42]:
len(a)

10

In [43]:
a.shape

(10,)

In [44]:
for value in a:
    print(value)

-0.4122332232292213
-2.3018076209286624
-0.5677374268058564
0.8430521231154835
0.0379234661348813
-0.8891140514089281
-0.5133150907803984
-1.0458645412179826
2.123852625112131
1.0175270933000709


### pandas 공부 2단계

`-` 데이터

In [45]:
np.random.seed(43052)
att = np.random.choice(np.arange(10,21)*5,20)
rep = np.random.choice(np.arange(5,21)*5,20)
mid = np.random.choice(np.arange(0,21)*5,20)
fin = np.random.choice(np.arange(0,21)*5,20)
key = ['202212'+str(s) for s in np.random.choice(np.arange(300,501),20,replace=False)]

In [46]:
df=pd.DataFrame({'att':att,'rep':rep,'mid':mid,'fin':fin},index=key)
df

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100
202212377   75   40  100   15
202212463   65   45   45   90
202212471   60   60   25    0
202212400   95   65   20   10
202212469   90   80   80   20
202212318   55   75   35   25
202212432   95   95   45    0
202212443   95   55   15   35
202212367   50   80   40   30
202212458   50   55   15   85
202212396   95   30   30   95
202212482   50   50   45   10
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

첫번째 칼럼을 선택

`-` 방법1

In [47]:
df.att

202212380    65
202212370    95
202212363    65
202212488    55
202212312    80
202212377    75
202212463    65
202212471    60
202212400    95
202212469    90
202212318    55
202212432    95
202212443    95
202212367    50
202212458    50
202212396    95
202212482    50
202212452    65
202212387    70
202212354    90
Name: att, dtype: int64

`-` 방법2 (딕셔너리스타일)

In [48]:
df['att']

202212380    65
202212370    95
202212363    65
202212488    55
202212312    80
202212377    75
202212463    65
202212471    60
202212400    95
202212469    90
202212318    55
202212432    95
202212443    95
202212367    50
202212458    50
202212396    95
202212482    50
202212452    65
202212387    70
202212354    90
Name: att, dtype: int64

`-` 방법3

In [49]:
df[['att']]

att
202212380   65
202212370   95
202212363   65
202212488   55
202212312   80
202212377   75
202212463   65
202212471   60
202212400   95
202212469   90
202212318   55
202212432   95
202212443   95
202212367   50
202212458   50
202212396   95
202212482   50
202212452   65
202212387   70
202212354   90

- df.att 나 df['att']는 series를 리턴하고 dff[['att']]는 dataframe을 리턴

`-` 방법4 : ndarray스타일

In [50]:
df.iloc[:,0]

202212380    65
202212370    95
202212363    65
202212488    55
202212312    80
202212377    75
202212463    65
202212471    60
202212400    95
202212469    90
202212318    55
202212432    95
202212443    95
202212367    50
202212458    50
202212396    95
202212482    50
202212452    65
202212387    70
202212354    90
Name: att, dtype: int64

`-` 방법5 : ndarray스타일

In [52]:
df.iloc[:,[0]]

att
202212380   65
202212370   95
202212363   65
202212488   55
202212312   80
202212377   75
202212463   65
202212471   60
202212400   95
202212469   90
202212318   55
202212432   95
202212443   95
202212367   50
202212458   50
202212396   95
202212482   50
202212452   65
202212387   70
202212354   90

- df.iloc[:,0]은 series를 리턴하고 df.iloc[:,[0]]은 dataframe을 리턴

`-` 방법 6 : ndarray 스타일과 dict 스타일의 혼합

In [53]:
df.loc[:,'att']

202212380    65
202212370    95
202212363    65
202212488    55
202212312    80
202212377    75
202212463    65
202212471    60
202212400    95
202212469    90
202212318    55
202212432    95
202212443    95
202212367    50
202212458    50
202212396    95
202212482    50
202212452    65
202212387    70
202212354    90
Name: att, dtype: int64

`-` 방법 7 : ndarray스타일과 dict 스타일의 혼합

In [54]:
df.loc[:,['att']]

att
202212380   65
202212370   95
202212363   65
202212488   55
202212312   80
202212377   75
202212463   65
202212471   60
202212400   95
202212469   90
202212318   55
202212432   95
202212443   95
202212367   50
202212458   50
202212396   95
202212482   50
202212452   65
202212387   70
202212354   90

- df.loc[:,'att']은 series를 리턴하고 df.loc[:,['att']]은 dataframe을 리턴

`-` 방법8 : np.array 스타일 + bool 인덱싱

In [55]:
df.iloc[:,[True,False,False,False]]

att
202212380   65
202212370   95
202212363   65
202212488   55
202212312   80
202212377   75
202212463   65
202212471   60
202212400   95
202212469   90
202212318   55
202212432   95
202212443   95
202212367   50
202212458   50
202212396   95
202212482   50
202212452   65
202212387   70
202212354   90

`-` 방법9 : ndarray와 dict의 혼합형 + bool 인덱싱

In [56]:
df.loc[:,[True,False,False,False]]

att
202212380   65
202212370   95
202212363   65
202212488   55
202212312   80
202212377   75
202212463   65
202212471   60
202212400   95
202212469   90
202212318   55
202212432   95
202212443   95
202212367   50
202212458   50
202212396   95
202212482   50
202212452   65
202212387   70
202212354   90

#### 여러개의 칼럼을 선택

`-` 방법1 : dict 스타일

In [57]:
df[['att','fin']]

att  fin
202212380   65   40
202212370   95   80
202212363   65   30
202212488   55   80
202212312   80  100
202212377   75   15
202212463   65   90
202212471   60    0
202212400   95   10
202212469   90   20
202212318   55   25
202212432   95    0
202212443   95   35
202212367   50   30
202212458   50   85
202212396   95   95
202212482   50   10
202212452   65   45
202212387   70   35
202212354   90   90

`-` 방법2 : ndarray 스타일 (정수리스트로 인덱싱, 슬라이싱, 스트라이딩)

In [58]:
df.iloc[:,[0,1]] #정수의 리스트를 전달하여 컬럼추출

att  rep
202212380   65   55
202212370   95  100
202212363   65   90
202212488   55   80
202212312   80   30
202212377   75   40
202212463   65   45
202212471   60   60
202212400   95   65
202212469   90   80
202212318   55   75
202212432   95   95
202212443   95   55
202212367   50   80
202212458   50   55
202212396   95   30
202212482   50   50
202212452   65   55
202212387   70   70
202212354   90   90

In [59]:
df.iloc[:,range(2)]

att  rep
202212380   65   55
202212370   95  100
202212363   65   90
202212488   55   80
202212312   80   30
202212377   75   40
202212463   65   45
202212471   60   60
202212400   95   65
202212469   90   80
202212318   55   75
202212432   95   95
202212443   95   55
202212367   50   80
202212458   50   55
202212396   95   30
202212482   50   50
202212452   65   55
202212387   70   70
202212354   90   90

In [60]:
df.iloc[:,:2]

att  rep
202212380   65   55
202212370   95  100
202212363   65   90
202212488   55   80
202212312   80   30
202212377   75   40
202212463   65   45
202212471   60   60
202212400   95   65
202212469   90   80
202212318   55   75
202212432   95   95
202212443   95   55
202212367   50   80
202212458   50   55
202212396   95   30
202212482   50   50
202212452   65   55
202212387   70   70
202212354   90   90

In [61]:
df.iloc[:,::2]

att  mid
202212380   65   50
202212370   95   50
202212363   65   60
202212488   55   75
202212312   80   30
202212377   75  100
202212463   65   45
202212471   60   25
202212400   95   20
202212469   90   80
202212318   55   35
202212432   95   45
202212443   95   15
202212367   50   40
202212458   50   15
202212396   95   30
202212482   50   45
202212452   65   15
202212387   70   40
202212354   90   80

`-` 방법3 : ndarray 와 dict의 혼합형

In [62]:
df.loc[:,['att','mid']]

att  mid
202212380   65   50
202212370   95   50
202212363   65   60
202212488   55   75
202212312   80   30
202212377   75  100
202212463   65   45
202212471   60   25
202212400   95   20
202212469   90   80
202212318   55   35
202212432   95   45
202212443   95   15
202212367   50   40
202212458   50   15
202212396   95   30
202212482   50   45
202212452   65   15
202212387   70   40
202212354   90   80

In [63]:
df.loc[:,'att':'mid']

att  rep  mid
202212380   65   55   50
202212370   95  100   50
202212363   65   90   60
202212488   55   80   75
202212312   80   30   30
202212377   75   40  100
202212463   65   45   45
202212471   60   60   25
202212400   95   65   20
202212469   90   80   80
202212318   55   75   35
202212432   95   95   45
202212443   95   55   15
202212367   50   80   40
202212458   50   55   15
202212396   95   30   30
202212482   50   50   45
202212452   65   55   15
202212387   70   70   40
202212354   90   90   80

In [64]:
df.loc[:,'rep':]

rep  mid  fin
202212380   55   50   40
202212370  100   50   80
202212363   90   60   30
202212488   80   75   80
202212312   30   30  100
202212377   40  100   15
202212463   45   45   90
202212471   60   25    0
202212400   65   20   10
202212469   80   80   20
202212318   75   35   25
202212432   95   45    0
202212443   55   15   35
202212367   80   40   30
202212458   55   15   85
202212396   30   30   95
202212482   50   45   10
202212452   55   15   45
202212387   70   40   35
202212354   90   80   90

`-` 방법4 : bool을 이용한 인덱싱

In [65]:
df.iloc[:,[True,False,True,False]]

att  mid
202212380   65   50
202212370   95   50
202212363   65   60
202212488   55   75
202212312   80   30
202212377   75  100
202212463   65   45
202212471   60   25
202212400   95   20
202212469   90   80
202212318   55   35
202212432   95   45
202212443   95   15
202212367   50   40
202212458   50   15
202212396   95   30
202212482   50   45
202212452   65   15
202212387   70   40
202212354   90   80

In [66]:
df.loc[:,[True,False,True,False]]

att  mid
202212380   65   50
202212370   95   50
202212363   65   60
202212488   55   75
202212312   80   30
202212377   75  100
202212463   65   45
202212471   60   25
202212400   95   20
202212469   90   80
202212318   55   35
202212432   95   45
202212443   95   15
202212367   50   40
202212458   50   15
202212396   95   30
202212482   50   45
202212452   65   15
202212387   70   40
202212354   90   80

#### 첫번째 행을 선택

`-` 방법1

In [67]:
df.iloc[0]

att    65
rep    55
mid    50
fin    40
Name: 202212380, dtype: int64

`-` 방법2

In [68]:
df.iloc[[0]]

att  rep  mid  fin
202212380   65   55   50   40

`-` 방법3

In [69]:
df.iloc[0,:]

att    65
rep    55
mid    50
fin    40
Name: 202212380, dtype: int64

`-` 방법4

In [70]:
df.iloc[[0],:]

att  rep  mid  fin
202212380   65   55   50   40

`-` 방법5

In [71]:
df.loc['202212380']

att    65
rep    55
mid    50
fin    40
Name: 202212380, dtype: int64

`-` 방법6

In [72]:
df.loc[['202212380']]

att  rep  mid  fin
202212380   65   55   50   40

`-` 방법7

In [73]:
df.loc['202212380',:]

att    65
rep    55
mid    50
fin    40
Name: 202212380, dtype: int64

`-` 방법8

In [75]:
df.loc[['202212380'],:]

att  rep  mid  fin
202212380   65   55   50   40

`-` 방법9

In [77]:
len(df)

20

In [78]:
_lst=[True]+[False]*19

In [79]:
df.iloc[_lst]

att  rep  mid  fin
202212380   65   55   50   40

In [80]:
df.iloc[_lst,:]

att  rep  mid  fin
202212380   65   55   50   40

In [81]:
df.loc[_lst]

att  rep  mid  fin
202212380   65   55   50   40

In [82]:
df.loc[_lst,:]

att  rep  mid  fin
202212380   65   55   50   40

#### 여러개의 행을 선택

`-` 방법1

In [83]:
df.iloc[[0,2]]

att  rep  mid  fin
202212380   65   55   50   40
202212363   65   90   60   30

In [84]:
df.iloc[[0,2],:]

att  rep  mid  fin
202212380   65   55   50   40
202212363   65   90   60   30

`-` 방법2

In [85]:
df.loc[['202212380','202212363']]

att  rep  mid  fin
202212380   65   55   50   40
202212363   65   90   60   30

In [86]:
df.loc[['202212380','202212363'],:]

att  rep  mid  fin
202212380   65   55   50   40
202212363   65   90   60   30

`-` 그 밖의 방법들

In [87]:
df.iloc[::3]

att  rep  mid  fin
202212380   65   55   50   40
202212488   55   80   75   80
202212463   65   45   45   90
202212469   90   80   80   20
202212443   95   55   15   35
202212396   95   30   30   95
202212387   70   70   40   35

In [88]:
df.iloc[:5]

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100

In [89]:
df.loc[:'202212312']

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100

In [90]:
df.loc[list(df.att<80),'rep':]

rep  mid  fin
202212380   55   50   40
202212363   90   60   30
202212488   80   75   80
202212377   40  100   15
202212463   45   45   90
202212471   60   25    0
202212318   75   35   25
202212367   80   40   30
202212458   55   15   85
202212482   50   45   10
202212452   55   15   45
202212387   70   40   35

In [91]:
df.loc[df.att<80,'rep':]

rep  mid  fin
202212380   55   50   40
202212363   90   60   30
202212488   80   75   80
202212377   40  100   15
202212463   45   45   90
202212471   60   25    0
202212318   75   35   25
202212367   80   40   30
202212458   55   15   85
202212482   50   45   10
202212452   55   15   45
202212387   70   40   35

In [92]:
df.iloc[list(df.att<80),1:]

rep  mid  fin
202212380   55   50   40
202212363   90   60   30
202212488   80   75   80
202212377   40  100   15
202212463   45   45   90
202212471   60   25    0
202212318   75   35   25
202212367   80   40   30
202212458   55   15   85
202212482   50   45   10
202212452   55   15   45
202212387   70   40   35

In [94]:
df.iloc[df.att<80,1:] #에러 발생

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

#### query ($\star$)

`-` 예제1

In [95]:
df.query('att==90 and mid >30')

att  rep  mid  fin
202212469   90   80   80   20
202212354   90   90   80   90

`-` 예제2

In [96]:
df.query('att<rep and mid <fin')

att  rep  mid  fin
202212370   95  100   50   80
202212488   55   80   75   80
202212458   50   55   15   85

`-` 예제3

In [98]:
df.query('att<rep<80 ')

att  rep  mid  fin
202212318   55   75   35   25
202212458   50   55   15   85

`-` 예제4

In [99]:
df.query('50 <att <= 90 and mid <fin')

att  rep  mid  fin
202212488   55   80   75   80
202212312   80   30   30  100
202212463   65   45   45   90
202212452   65   55   15   45
202212354   90   90   80   90

`-` 예제5

In [100]:
df.query('(mid+fin)/2 >=60')

att  rep  mid  fin
202212370   95  100   50   80
202212488   55   80   75   80
202212312   80   30   30  100
202212463   65   45   45   90
202212396   95   30   30   95
202212354   90   90   80   90

`-` 예제6

In [101]:
_mean=df.att.mean()
_mean

73.0

In [102]:
df.query('att>=73')

att  rep  mid  fin
202212370   95  100   50   80
202212312   80   30   30  100
202212377   75   40  100   15
202212400   95   65   20   10
202212469   90   80   80   20
202212432   95   95   45    0
202212443   95   55   15   35
202212396   95   30   30   95
202212354   90   90   80   90

In [103]:
df.query('att>= @_mean')

att  rep  mid  fin
202212370   95  100   50   80
202212312   80   30   30  100
202212377   75   40  100   15
202212400   95   65   20   10
202212469   90   80   80   20
202212432   95   95   45    0
202212443   95   55   15   35
202212396   95   30   30   95
202212354   90   90   80   90

- 주의 _mean 이라고 하면 실행되지 않음

`-` 예제7

In [104]:
df

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100
202212377   75   40  100   15
202212463   65   45   45   90
202212471   60   60   25    0
202212400   95   65   20   10
202212469   90   80   80   20
202212318   55   75   35   25
202212432   95   95   45    0
202212443   95   55   15   35
202212367   50   80   40   30
202212458   50   55   15   85
202212396   95   30   30   95
202212482   50   50   45   10
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

In [105]:
df.query("index <= '202212354' or index =='202212387' ")

att  rep  mid  fin
202212312   80   30   30  100
202212318   55   75   35   25
202212387   70   70   40   35
202212354   90   90   80   90

이 기능은 시계열자료에서 가장 유용

`-` 예제8

In [107]:
pd.date_range('20211226',periods=10)

DatetimeIndex(['2021-12-26', '2021-12-27', '2021-12-28', '2021-12-29',
               '2021-12-30', '2021-12-31', '2022-01-01', '2022-01-02',
               '2022-01-03', '2022-01-04'],
              dtype='datetime64[ns]', freq='D')

In [109]:
_df=pd.DataFrame(np.random.normal(size=(10,4)),columns=list('ABCD'),index=pd.date_range('20211226',periods=10))
_df        

A         B         C         D
2021-12-26  0.117038 -0.350165  0.410882 -0.763975
2021-12-27  0.766821  1.032189  0.404380 -0.134916
2021-12-28 -0.767637 -0.642942 -0.247824 -1.457658
2021-12-29 -0.091060  0.323402 -0.774021  0.659558
2021-12-30 -0.794595 -2.605380  0.283726 -1.832944
2021-12-31  0.292831  0.287421  0.283594 -0.746875
2022-01-01 -0.918335  0.402325  0.485921  0.122862
2022-01-02 -0.701718  0.740156 -0.898490  1.038380
2022-01-03 -0.441720  0.319821  0.705463 -0.027263
2022-01-04 -0.148996  0.234815 -1.412675 -0.706377

In [110]:
_df.query("'2021-12-29' <= index <= '2022-01-03' ")

A         B         C         D
2021-12-29 -0.091060  0.323402 -0.774021  0.659558
2021-12-30 -0.794595 -2.605380  0.283726 -1.832944
2021-12-31  0.292831  0.287421  0.283594 -0.746875
2022-01-01 -0.918335  0.402325  0.485921  0.122862
2022-01-02 -0.701718  0.740156 -0.898490  1.038380
2022-01-03 -0.441720  0.319821  0.705463 -0.027263

In [112]:
_df.query("'2021-12-29' <= index <= '2022-01-03' and A+B<C")

A         B         C         D
2021-12-30 -0.794595 -2.605380  0.283726 -1.832944
2022-01-01 -0.918335  0.402325  0.485921  0.122862
2022-01-03 -0.441720  0.319821  0.705463 -0.027263

`-` query가 만능은 아니다.

In [113]:
df.columns=pd.Index(['att score', 'rep score', 'mid score', 'fin score'])

In [114]:
df.query("att score < 90 ")
# df.loc[df['att score'] < 90, :] <-- 이렇게 구현하면 가능 (아니면 변수이름을 바꿔주는 코드를 짜면 됨)

SyntaxError: invalid syntax (<unknown>, line 1)

### pandas 공부 3단계

#### 전치

In [115]:
ndarray=np.arange(2*3).reshape(2,3)
df=pd.DataFrame(ndarray)
df

0  1  2
0  0  1  2
1  3  4  5

In [116]:
ndarray.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [117]:
df.T

0  1
0  0  3
1  1  4
2  2  5

합

In [118]:
ndarray.sum(axis=0)

array([3, 5, 7])

In [119]:
df.sum(axis=0)

0    3
1    5
2    7
dtype: int64

In [120]:
ndarray.sum(axis=1)

array([ 3, 12])

In [121]:
df.sum(axis=1)

0     3
1    12
dtype: int64

cumsum

In [122]:
df

0  1  2
0  0  1  2
1  3  4  5

In [123]:
ndarray.cumsum(axis=0)

array([[0, 1, 2],
       [3, 5, 7]])

In [124]:
df.cumsum(axis=0)

0  1  2
0  0  1  2
1  3  5  7

In [125]:
ndarray.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12]])

In [126]:
df.cumsum(axis=1)

0  1   2
0  0  1   3
1  3  7  12

형태변환

In [127]:
ndarray.tolist()

[[0, 1, 2], [3, 4, 5]]

In [128]:
df.to_dict()

{0: {0: 0, 1: 3}, 1: {0: 1, 1: 4}, 2: {0: 2, 1: 5}}

In [129]:
df.to_numpy()

array([[0, 1, 2],
       [3, 4, 5]])

In [130]:
df.to_numpy().tolist()

[[0, 1, 2], [3, 4, 5]]